### ISSUE TITLE
Github hosting

### ISSUE THREAD

**Issue by gjreasoner** [beschizza/charactercreationisthewholegame#2]
You can host this game for people to play it easier with github using their 'github pages' feature, just go to [Settings](https://github.com/beschizza/charactercreationisthewholegame/settings) -> GitHub Pages -> Click on 'None' from 'Sources' -> Choose 'master branch' and hit save.

Then you should be able to go the link https://beschizza.github.io/charactercreationisthewholegame/game.html

I forked the repo to try it out myself you can see it here; https://gjrdiesel.github.io/charactercreationisthewholegame/game.html

![screen shot 2017-02-23 at 2 35 17 am](https://cloud.githubusercontent.com/assets/3363867/23249132/c19bbefa-f970-11e6-89f9-33a9d6fb505a.png)

Then just update your readme and add a link to the top so people can play it. Neat game/design!

**Comment by beschizza** [comment]
Thank you, Justin! I appreciate this a lot -- still getting to grips with
github!

**Comment by beschizza** [comment]
Done! Magic!
