### ISSUE TITLE
Taking your stats below 8 and spending all the points allows you to go into negative points

### ISSUE THREAD

**Issue by HasBrian** [beschizza/charactercreationisthewholegame#4]
-300 is my best so far.

Repro:
STR/DEX/INT/WIS all to 3 or lower. Then raise CHA up as fast as possible. It'll continue past the max points available.

**Comment by objectsforheads** [comment]
I had a quick go at this the other day, trying to figure out the exact reason.

It could be that the calculation to figure out when to show the increase/decrease arrow only happens when `nextTurn()` runs, which only runs when a pop-up event happens. So if you happen to not get a story on the turn you drop to 0 points, it just lets you keep going because the arrows remain and there's no check to make sure your available points is greater than 0.

IIRC, you get events usually when your stats > 7/8, so when you drop below that threshold you disqualify your character for the events that would trigger the nextTurn check.

**Comment by HasBrian** [comment]
I just tested again. I found that you can also push stats negative. I just ran a character with -150 INT, 300 STR, 40 DEX which was forced to retire at the ripe old age of 682!

**Comment by HasBrian** [comment]
![screen shot 2017-03-10 at 10 28 15 am](https://cloud.githubusercontent.com/assets/5176442/23807872/4dea5a3a-057c-11e7-8790-f91bc2363227.png)

**Comment by kasaiken** [comment]
I found this glitch as well, and I finished a patch for this and it works. I'm a high school student in 9th grade. And by the way, there's another way to do this glitch, just add all points to DEX and then remove all points as possible from CHA and add them to DEX and then do the same to with WIS and it will work after that.
`
//
	if(character.points == 0){
	document.getElementById("arrowSTRup").style.display = "none";
	document.getElementById("arrowDEXup").style.display = "none";
	document.getElementById("arrowINTup").style.display = "none";
	document.getElementById("arrowWISup").style.display = "none";
	document.getElementById("arrowCHAup").style.display = "none";		
	}else{
	document.getElementById("arrowSTRup").style.display = "inline";
	document.getElementById("arrowDEXup").style.display = "inline";
	document.getElementById("arrowINTup").style.display = "inline";
	document.getElementById("arrowWISup").style.display = "inline";
	document.getElementById("arrowCHAup").style.display = "inline";	
	}
	
	if(character.STR == 6){document.getElementById("arrowSTRdown").style.display = "none";}
	if(character.DEX == 6){document.getElementById("arrowDEXdown").style.display = "none";}
	if(character.INT == 6){document.getElementById("arrowINTdown").style.display = "none";}
	if(character.WIS == 6){document.getElementById("arrowWISdown").style.display = "none";}
	if(character.CHA == 6){document.getElementById("arrowCHAdown").style.display = "none";}
	//
`
that's the complete patch, it works and you cant get around it. I'm submitting the patch now.

**Comment by beschizza** [comment]
Brilliant

**Comment by beschizza** [comment]
Thank you again, I can no longer reproduce the glitch!
